package pt.isec.pa.tinypac.model.fsm;

public enum GameStates {
    INITIAL,GAME_OVER,EATING_FRUIT, EATING_POINT,EATING_POWER, GHOST_COLISION,WRAP_ZONE,PLAYING,LEVEL_UP, EATING_GHOST, VULNERABILITY
}
